version: '3.8'

services:
  # PostgreSQL Database
  db:
    image: postgres:15-alpine
    restart: unless-stopped
    environment:
      POSTGRES_DB: canil_db
      POSTGRES_USER: canil_user
      POSTGRES_PASSWORD: canil_password
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U canil_user -d canil_db"]
      interval: 10s
      timeout: 5s
      retries: 5

  # Redis for caching and Celery
  redis:
    image: redis:7-alpine
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 3

  # Flask Application
  web:
    build: .
    restart: unless-stopped
    ports:
      - "8000:8000"
    environment:
      - FLASK_ENV=production
      - DATABASE_URL=postgresql://canil_user:canil_password@db:5432/canil_db
      - REDIS_URL=redis://redis:6379/0
      - SECRET_KEY=your-super-secret-key-change-this
      - JWT_SECRET_KEY=your-jwt-secret-key-change-this
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy
    volumes:
      - ./logs:/app/logs
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  # Celery Worker
  celery:
    build: .
    restart: unless-stopped
    command: celery -A app.celery_worker worker --loglevel=info
    environment:
      - FLASK_ENV=production
      - DATABASE_URL=postgresql://canil_user:canil_password@db:5432/canil_db
      - REDIS_URL=redis://redis:6379/0
      - SECRET_KEY=your-super-secret-key-change-this
    depends_on:
      - db
      - redis
    volumes:
      - ./logs:/app/logs

  # Celery Beat Scheduler
  celery-beat:
    build: .
    restart: unless-stopped
    command: celery -A app.celery_worker beat --loglevel=info
    environment:
      - FLASK_ENV=production
      - DATABASE_URL=postgresql://canil_user:canil_password@db:5432/canil_db
      - REDIS_URL=redis://redis:6379/0
      - SECRET_KEY=your-super-secret-key-change-this
    depends_on:
      - db
      - redis
    volumes:
      - ./logs:/app/logs

  # Nginx Reverse Proxy (optional)
  nginx:
    image: nginx:alpine
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./ssl:/etc/nginx/ssl:ro
    depends_on:
      - web
    profiles:
      - production

volumes:
  postgres_data:
  redis_data:

networks:
  default:
    name: canil_network